# Generated by Django 3.1.5 on 2021-01-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('Adhar', models.ImageField(upload_to='', verbose_name='img/%Y%Y%Y%')),
                ('Pan', models.ImageField(upload_to='', verbose_name='img/%Y%Y%Y%')),
                ('PassBookFirstPage', models.ImageField(upload_to='', verbose_name='img/%Y%Y%Y%')),
            ],
        ),
    ]
