# Generated by Django 3.1.5 on 2021-01-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendence', models.DateField()),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('Adhar', models.ImageField(upload_to='', verbose_name='Adhar_card')),
                ('Pan', models.ImageField(upload_to='', verbose_name='Pan_card')),
                ('PassBookFirstPage', models.ImageField(upload_to='', verbose_name='PassBookFirstPage')),
            ],
        ),
    ]
