# Generated by Django 3.1.5 on 2021-01-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Adhar',
            field=models.ImageField(upload_to='', verbose_name='Adhar_card'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Pan',
            field=models.ImageField(upload_to='', verbose_name='Pan_card'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PassBookFirstPage',
            field=models.ImageField(upload_to='', verbose_name='PassBookFirstPage'),
        ),
    ]
